version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: insurance_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
